author: Nimiq Community
copyright: Copyright (c) 2020 Nimiq Community

module: NimiqClientMacOS

theme: fullwidth
clean: true

readme: README.md

hide_documentation_coverage: true

xcodebuild_arguments: [-workspace, NimiqClient/NimiqClient.xcworkspace, -scheme, NimiqClientMacOS]
