language: swift
osx_image: xcode10.2
xcode_workspace: NimiqClient/NimiqClient.xcworkspace
matrix:
  include:
  - xcode_scheme: NimiqClientMacOS
    xcode_sdk: macosx10.14
    env: DESTINATION="platform=macOS,arch=x86_64"
  - xcode_scheme: NimiqClientiOS
    xcode_sdk: iphonesimulator12.0
    env: DESTINATION="platform=iOS Simulator,OS=12.0,name=iPhone XS"
  - xcode_scheme: NimiqClientiOS
    xcode_sdk: iphonesimulator12.0
    env: DESTINATION="platform=iOS Simulator,OS=11.4,name=iPhone 8"
  - xcode_scheme: NimiqClientiOS
    xcode_sdk: iphonesimulator12.0
    env: DESTINATION="platform=iOS Simulator,OS=10.3.1,name=iPhone 7"
  - xcode_scheme: NimiqClientiOS
    xcode_sdk: iphonesimulator12.0
    env: DESTINATION="platform=iOS Simulator,OS=9.3,name=iPhone 6s"
  - xcode_scheme: NimiqClientTvOS
    xcode_sdk: appletvsimulator12.0
    env: DESTINATION="platform=tvOS Simulator,OS=12.0,name=Apple TV"
script:
  - set -o pipefail
  - xcodebuild clean build build-for-testing -workspace "${TRAVIS_XCODE_WORKSPACE}" -scheme "${TRAVIS_XCODE_SCHEME}" -sdk "${TRAVIS_XCODE_SDK}" -destination "${DESTINATION}" | xcpretty
  - xcodebuild test-without-building -workspace "${TRAVIS_XCODE_WORKSPACE}" -scheme "${TRAVIS_XCODE_SCHEME}" -sdk "${TRAVIS_XCODE_SDK}" -destination "${DESTINATION}" | xcpretty
