language: swift
osx_image: xcode11.5
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - WORKSPACE=NimiqClient/NimiqClient.xcworkspace
  - IOS_SCHEME="NimiqClientiOS"
  - IOS_SDK=iphonesimulator9.2
  - OSX_SCHEME="NimiqClientMacOS"
  - OSX_SDK=macosx10.11
  - TVOS_SCHEME="NimiqClientTvOS"
  - TVOS_SDK=appletvsimulator9.1
  matrix:
    - DESTINATION="OS=9.2,name=iPad Pro (9.7-inch)" SCHEME="$IOS_SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="YES" POD_LINT="NO"
    - DESTINATION="OS=9.2,name=iPhone 11"           SCHEME="$IOS_SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="YES" POD_LINT="NO"
    - DESTINATION="arch=x86_64"                     SCHEME="$OSX_SCHEME"     SDK="$OSX_SDK"     RUN_TESTS="YES" POD_LINT="NO"
    - DESTINATION="OS=9.1,name=Apple TV"            SCHEME="$TVOS_SCHEME"    SDK="$TVOS_SDK"    RUN_TESTS="YES" POD_LINT="NO"

script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks

  - if [ $RUN_TESTS == "YES" ]; then
      xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO test | xcpretty -c;
    else
      xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty -c;
    fi

  - if [ $POD_LINT == "YES" ]; then
      pod lib lint --private --verbose;
    fi
