name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macOS-latest

    strategy:
      matrix:
        destination: [
          'platform=macOS,arch=x86_64',
          'platform=iOS Simulator,OS=13.6,name=iPhone 8',
          'platform=iOS Simulator,OS=13.6,name=iPad (7th generation)',
          'platform=tvOS Simulator,OS=13.4,name=Apple TV'
        ]

    steps:
      - uses: actions/checkout@main
      - name: Build and test
        env: 
          destination: ${{ matrix.destination }}
        run: |
          xcodebuild test -project "NimiqClient.xcodeproj" -scheme "NimiqClient-Package" -destination "${destination}" -configuration Debug -enableCodeCoverage YES -resultBundlePath coverage/result.xcresult
          xcrun xccov view --report --json coverage/result.xcresult > coverage/lcov.json
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
